version: '3'
services:
  frontend:
    build:
      context: ./grocery-sale-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./grocery
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
